package xyz.cofe.term.win;

public enum InputModeFlags implements BitFlag {
    /**
     * Characters read by the ReadFile or ReadConsole function are
     * written to the active screen buffer as they are typed into the console.
     * <p>
     * This mode can be used only if the ENABLE_LINE_INPUT mode is also enabled.
     */
    ENABLE_ECHO_INPUT(0x0004),

    /**
     * When enabled, text entered in a console window will be inserted at
     * the current cursor location and all text following that location will not be overwritten.
     * <p>
     * When disabled, all following text will be overwritten.
     */
    ENABLE_INSERT_MODE(0x0020),

    /**
     * The ReadFile or ReadConsole function returns only when
     * a carriage return character is read.
     * <p>
     * If this mode is disabled, the functions return when one or more characters are available.
     */
    ENABLE_LINE_INPUT(0x0002),

    /**
     * If the mouse pointer is within the borders of the console window and
     * the window has the keyboard focus, mouse events generated by mouse movement and
     * button presses are placed in the input buffer.
     * <p>
     * These events are discarded by ReadFile or ReadConsole, even when this mode is enabled.
     * <p>
     * The ReadConsoleInput function can be used to read MOUSE_EVENT input records from the input buffer.
     */
    ENABLE_MOUSE_INPUT(0x0010),

    /**
     * CTRL+C is processed by the system and is not placed in the input buffer.
     * <p>
     * If the input buffer is being read by ReadFile or ReadConsole, other control keys are
     * processed by the system and are not returned in the ReadFile or ReadConsole buffer.
     * <p>
     * If the ENABLE_LINE_INPUT mode is also enabled, backspace, carriage return,
     * and line feed characters are handled by the system.
     */
    ENABLE_PROCESSED_INPUT(0x0001),

    /**
     * This flag enables the user to use the mouse to select and edit text.
     * <p>
     * To enable this mode, use ENABLE_QUICK_EDIT_MODE | ENABLE_EXTENDED_FLAGS.
     * <p>
     * To disable this mode, use ENABLE_EXTENDED_FLAGS without this flag.
     */
    ENABLE_QUICK_EDIT_MODE(0x0040),

    /**
     * User interactions that change the size of the console screen buffer are
     * reported in the console's input buffer.
     * <p>
     * Information about these events can be read from the input buffer
     * by applications using the ReadConsoleInput function,
     * but not by those using ReadFile or ReadConsole.
     */
    ENABLE_WINDOW_INPUT(0x0008),

    /**
     * Setting this flag directs the Virtual Terminal processing engine
     * to convert user input received by the console window into Console Virtual Terminal Sequences that
     * can be retrieved by a supporting application through ReadFile or ReadConsole functions.
     * <p>
     * The typical usage of this flag is intended in conjunction with ENABLE_VIRTUAL_TERMINAL_PROCESSING on
     * the output handle to connect to an application
     * that communicates exclusively via virtual terminal sequences.
     */
    ENABLE_VIRTUAL_TERMINAL_INPUT(0x0200);

    private final int bitFlag;

    @Override
    public int bitFlag() {
        return bitFlag;
    }

    InputModeFlags(int bitFlag) {
        this.bitFlag = bitFlag;
    }
}
